kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: build-my-java
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'my-java-image-stream:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-11-el7'
