kind: Service
apiVersion: v1
metadata:
  name: service-for-java
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    deployment: java-app
