kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: java-template-for-route
objects:
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: route-for-java
    annotations:
      openshift.io/host.generated: 'true'
  spec:
    to:
      kind: Service
      name: service-for-java
      weight: 100
    port:
      targetPort: 8080
    wildcardPolicy: None
parameters:
  - description: namepace
    generate: expression
    name: OPENSHIFT_NAMESPACE
